# Generated by Django 2.1.2 on 2023-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default=' ', max_length=256, verbose_name='ファイル名')),
                ('file_path', models.CharField(blank=True, default=' ', max_length=256, verbose_name='ファイルの場所')),
                ('title', models.CharField(blank=True, default=' ', max_length=256, verbose_name='タイトル')),
                ('actor_name', models.CharField(blank=True, default=' ', max_length=256, verbose_name='主演')),
                ('search_str', models.CharField(blank=True, default=' ', max_length=256, verbose_name='検索文字列')),
                ('movie_time', models.IntegerField(blank=True, default=360, verbose_name='再生時間')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, default=' ', max_length=256, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='TagRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default=' ', max_length=256, verbose_name='ファイル名')),
                ('tag_name', models.CharField(blank=True, default=' ', max_length=256, verbose_name='タグ')),
            ],
        ),
    ]
