# Generated by Django 2.1.2 on 2023-03-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagLabel',
        ),
    ]
